### ISSUE TITLE
How to use the human demonstrations for imitation learning?

### ISSUE THREAD

**Issue by maguro27** [StanfordVL/BehaviorChallenge2021#10]
Although I downloaded the human demonstrations, I cannot find how to implement imitation learning in this repository and the iGibson repository.
Is there a usage of the human demonstrations for imitation learning?

Thanks.

**Comment by mjlbach** [comment]
Thanks for your interest! We haven't provided baselines yet for imitation learning. When we do, we will announce it along with a behavior-baselines repository. Feel free to provide your own experience here if you have any results to share!

**Comment by cgokmen** [comment]
Hi @maguro27 , we are building a set of baselines as Michael mentioned, and one of our colleagues is working currently on a Behavioral Cloning baseline that you might find helpful. Here is their work-in-progress code: https://github.com/StanfordVL/behavior-baselines/pull/2

**Comment by maguro27** [comment]
@cgokmen 
I appreciate your tremendous help!
I try using your baseline script.
