### ISSUE TITLE
Unable to run stable_baselines3_example.py

### ISSUE THREAD

**Issue by asfandasfo** [StanfordVL/BehaviorChallenge2021#12]
Hi, I am trying to run the stable_baselines3_example.py file but have this error.
![Error](https://user-images.githubusercontent.com/11736209/134817199-349e3258-cdb2-4be4-b0fa-76ecf6a79197.png)

**Comment by mjlbach** [comment]
Seems like there’s an issue with decrypted our encrypted assets. Where did you put igibson.key that you should have received after signing the iGibson agreement?

**Comment by asfandasfo** [comment]
as suggested in igibson/data

**Comment by asfandasfo** [comment]
![erro2](https://user-images.githubusercontent.com/11736209/134817495-b59edebe-818b-4e2a-a4b9-156e069934c8.PNG)
