### ISSUE TITLE
The shape of "proprioception" of the human demonstration does not match "proprioception" from an agent.

### ISSUE THREAD

**Issue by maguro27** [StanfordVL/BehaviorChallenge2021#13]
Although I used the human demonstration for imitation learning, the proprioception observation data of the human demonstration do not match the shape with proprioception observation data from an agent.
In [the BEHAVIOR challenge guideline](https://docs.google.com/document/d/1u2m9Ld6Qo3eG-fvCzuAZN6lHxwpVVBlwLVdzo_WDlNI/edit#heading=h.t7d09kkc5vnx), the shape of the proprioception observation data is (N x 20).
However, the shape of proprioception data from an agent is (N x 22).
Which of the data shapes are correct?
Additionally, how do I fix it?

The debugging method is that I add the following script into [after L.93 of the stable_baselines3_behavior_example.py](https://github.com/StanfordVL/iGibson/blob/master/igibson/examples/demo/stable_baselines3_behavior_example.py#L93).
```
if key == "proprioception":
    print(observations[key].shape)
```

Thanks.

**Comment by maguro27** [comment]
Moreover, the shape of the action data of the human demonstration does not match the shape with action data from an agent.
Agent: (N x 26)
human demonstration: (N x 28)

In the BEHAVIOR challenge guideline, the Behavior robot DoF is 28.
Is an agent output wrong?

**Comment by mjlbach** [comment]
Hi,

We updated the proprioception data on ig-develop to include objects in hand, but haven’t updated the dataset or documentation yet (the former is up, just not publicly available). 

We mask out the 2 hand reset actions which is why the dimension of the action space is 26, not 28.

Best,
Michael

**Comment by maguro27** [comment]
@mjlbach 
Thank you for your response!
In the action data (N x 28) of the human demonstration, where are hand reset actions? Final two array? (27 and 28 are hand reset actions?)

**Comment by maguro27** [comment]
@mjlbach 
Additionally, when will you upload the updated version of the human demonstration?

**Comment by corgiTrax** [comment]
> @mjlbach Thank you for your response! In the action data (N x 28) of the human demonstration, where are hand reset actions? Final two array? (27 and 28 are hand reset actions?)

These are dimension 19 and 27 (starting from 0, see https://github.com/StanfordVL/iGibson/blob/master/igibson/envs/behavior_env.py#L216)

**Comment by maguro27** [comment]
@mjlbach 
Excuse me.
I want to know when will you upload the updated version of the human demonstration.
I may not make it in time because I have a few computation resources.
Please tell me an approximate date for uploading the files.

**Comment by mjlbach** [comment]
They’re in the process of being uploaded right now, at the current rate I estimate they will be done within the next 2 hours. I have to lift the ACL once they are finished uploading, so it won’t be available until tomorrow PST (around 9 am I’d guess), at which point you can fetch the latest dataset with gustil:

gsutil -m rsync gs://gibsonchallenge/behavior_human_demos_v0.3.0 ./behavior_human_demos_v0.3.0

**Comment by mjlbach** [comment]
The ACL is updated, you can download with `gsutil -m rsync gs://gibsonchallenge/behavior_human_demos_v0.3.0 ./behavior_human_demos_v0.3.0`

Note I'll be uploading one more round of demos, but it may not be before the end of the challenge. These will be additional/improved demos addressing some concerns about the camera angle from the HMD.
