### ISSUE TITLE
Cannot evaluate an agent.

### ISSUE THREAD

**Issue by maguro27** [StanfordVL/BehaviorChallenge2021#14]
Hi.
I cannot evaluate an agent when I ran [the agnet.py](https://github.com/StanfordVL/BehaviorChallenge2021/blob/master/agent.py).
The returned std output is as follows,

```
No openable joint metadata found for object jar-03_14-0
No openable joint metadata found for object jar-03_4-1
No openable joint metadata found for object jar-03_15-2
No openable joint metadata found for object jar-03_0-3
No openable joint metadata found for object jar-03_9-4
No openable joint metadata found for object jar-03_10-5
```

The script was freeze after I got the above std output.
How do I fix it?
Note that I downloaded the `ig_dataset` from the behavior_data_bundle.zip of [this form](https://forms.gle/ecyoPtEcCBMrQ3qF9).

Some environment variables are as follows,
```
export SPLIT=minival
export CONFIG_FILE=/opt/iGibson/igibson/examples/configs/behavior_onboard_sensing.yaml
export OUTPUT_DIR={$my_directory}/BehaviorChallenge2021/results
```

Thanks.

**Comment by fxia22** [comment]
@maguro27 I think it is normal, the evaluation is running and can take a long time to finish evaluating. 

You can add a print out to this line https://github.com/StanfordVL/iGibson/blob/master/igibson/challenge/behavior_challenge.py#L125 so every step will show some prints.

In the docker it is in `/opt/iGibson/igibson/challenge/behavior_challenge.py`

**Comment by cgokmen** [comment]
The quoted error messages are not representative of a problem & we will clean this up. Thank you for the report there.

**Comment by maguro27** [comment]
@fxia22 
I appreciate your response!
I can evaluate an agent when I continued running the script.

Additionally, please tell me how many times does the agent.py takes per household activity if you know the approximate time.
I'm running the agent.py for about 2 hours now.

**Comment by maguro27** [comment]
Excuse me.
I complete the evaluation just now.
It takes about 2.5 hours in the mine environment.
Thanks.
