### ISSUE TITLE
Human demonstrations data format

### ISSUE THREAD

**Issue by phj128** [StanfordVL/BehaviorChallenge2021#4]
Hi, I've downloaded the data of human demonstrations. However the data format is not consistent with the google doc. `hf[‘frame_data’][‘vr_device_data’][‘hmd’][frame_number, 1:4]` does not exist while I only get `hf['action']`, `hf['rgb']` ...

**Comment by mjlbach** [comment]
What you want is the "raw" observations, which include the HMD data. I updated the participant guide with a description of the keys for the processed observations which match the sensor modalities of the agent.

You can fetch the raw observations with:
`gsutil -m rsync gs://gibsonchallenge/behavior_human_demos_raw ./behavior_human_demos_raw`

**Comment by phj128** [comment]
`gs://gibsonchallenge/behavior_human_demos_raw` seems empty that I cannot download the data.

**Comment by mjlbach** [comment]
I checked the ACL and it seems fine from our end. What does:

`gsutil ls 'gs://gibsonchallenge/behavior_human_demos_raw/*' ` show for you?

**Comment by phj128** [comment]
It is `gs://gibsonchallenge/behavior_human_demos_raw/behavior_human_demons_raw/`. 
I can download data by `gs://gibsonchallenge/behavior_human_demos_raw/behavior_human_demons_raw/` now. 
Thanks for your help.

**Comment by mjlbach** [comment]
Whoops, sorry. Misnamed the folder, just moved the demos to the top level subfolder.
