### ISSUE TITLE
json File Error

### ISSUE THREAD

**Issue by harryzhangOG** [StanfordVL/BehaviorChallenge2021#6]
Hi, when I was running the igibson/examples/behavior/behavior_env_metrics.py file, line 95 is causing an error that float32 cannot be dumped into a json. So i changed line 95 to   json.dump(str(per_episode_metrics), file). But now the json file becomes unreadable. 

https://stackoverflow.com/questions/53082708/typeerror-object-of-type-float32-is-not-json-serializable

**Comment by fxia22** [comment]
Hi @harryzhangOG thanks for reporting, we are working on fixing this issue.

**Comment by fxia22** [comment]
@harryzhangOG can you test again on [StanfordVL/iGibson](https://github.com/StanfordVL/iGibson) `ig-develop` branch? If you still see this issue, can you provide a script to reproduce and @mjlbach and I can take a look. Thanks!

**Comment by mjlbach** [comment]
I think this issue has been resolved, but feel free to reopen with a repro if not
