### ISSUE TITLE
How to visualize a trained model?

### ISSUE THREAD

**Issue by maguro27** [StanfordVL/BehaviorChallenge2021#7]
I appreciate your great work!
I have a question.

Although I already trained the robots, I don't know how to visualize the trained model.
Please teach me visualization methods.

Thanks.

**Comment by ChengshuLi** [comment]
Hi, you can instantiate the BehaviorEnv with mode="gui". You will be able to visualize the trained model in pybullet GUI and also iGibson GUI.

**Comment by maguro27** [comment]
I appreciate your response!
I solved it!
