### ISSUE TITLE
issue with test_minival_locally

### ISSUE THREAD

**Issue by ericrosenbrown** [StanfordVL/BehaviorChallenge2021#8]
Hello,

I tried to build the included Docker file using the command:

docker build . -t first_attempt

Everything seemed to go fine with the Docker build, but then when I run:

/test_minival_locally.sh --docker-name first_attempt

I get the following error:
ModuleNotFoundError: No module named 'py360convert'

However, my virtual environment for iGibson has py360convert (i can import it in my python files), what would be causing this issue?

**Comment by fxia22** [comment]
Hi Eric, this is an error we introduced in a recent update. I just fixed it, if you pull `igibson/behavior_challenge_2021:latest` again and build your docker again it should work. Let me know if it doesn't.

**Comment by ericrosenbrown** [comment]
How do we pull this update? We run "git pull" in the folder but it says it is already up to date on the master branch, and there does not appear to be a igibson/behavior_challenge_2021:latest branch on the online repo? To clarify, we built from source. Thanks!

**Comment by fxia22** [comment]
@ericrosenbrown you can run `docker pull igibson/behavior_challenge_2021:latest` and then rebuild your docker with `docker build . -t first_attempt`. Thanks.
